/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Role = "guest" | "member" | "org_admin";

export type Sysrole = "sysadmin" | "user";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface LoginAttempts {
  attempt_time: Generated<Timestamp | null>;
  email: string;
  error_message: string | null;
  id: Generated<string>;
  ip_address: string;
  successful: boolean;
}

export interface Members {
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  member_role: Role;
  org_id: string | null;
  user_id: string | null;
}

export interface Orgs {
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  name: string;
  slug: string;
}

export interface SchemaMigrations {
  dirty: boolean;
  version: Int8;
}

export interface Sessions {
  created_at: Generated<Timestamp | null>;
  expires_at: Timestamp;
  id: Generated<string>;
  token_hash: string;
  user_id: string | null;
}

export interface Users {
  created_at: Generated<Timestamp | null>;
  email: string;
  id: Generated<string>;
  password_hash: string;
  system_role: Generated<Sysrole>;
  username: string;
}

export interface DB {
  login_attempts: LoginAttempts;
  members: Members;
  orgs: Orgs;
  schema_migrations: SchemaMigrations;
  sessions: Sessions;
  users: Users;
}
